name: "Release @nibiruchain/* packages"

on:
  push:
    branches: "release/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v* such as v3, v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup NodeJS and npm
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install yarn using npm
        run: npm install -g yarn
      - name: Setup NodeJS with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build the application
        run: yarn build
