name: Run all tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS and npm
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install yarn using npm
        run: npm install -g yarn
      - name: Setup NodeJS with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build the application
        run: yarn build
      - name: test sdk.Dec conversions in the common package
        run: yarn test -t 'SdkDec'
      - name: test node connections with http
        run: yarn test -t 'node connection'
